### ISSUE TITLE
Remove 'unranked' teams concept

### ISSUE THREAD

**Issue by Lordfirespeed** [ducompsoc/durhack-jury#1]
### Describe the feature you'd like

Teams that are not available for judging should not be penalised

**Comment by tameTNT** [comment]
The new system discussed which allows teams to mark themselves as not available and skips including them in the ranking 'batch' covers this.

**Comment by Lordfirespeed** [comment]
That's not entirely true - there is implementation we need to strip out relating to the 'judging' model keeping track of 'Unranked' teams (teams that were skipped)
